const librosArte = [{"isbn": "", "codigo": "", "cantidad": "", "titulo": "", "autor": "", "precio": ""},
                    {"isbn": "", "codigo": "", "cantidad": "", "titulo": "", "autor": "", "precio": ""},
                    {"isbn": "", "codigo": "", "cantidad": "", "titulo": "", "autor": "", "precio": ""},
                    {"isbn": "", "codigo": "", "cantidad": "", "titulo": "", "autor": "", "precio": ""},
                    {"isbn": "", "codigo": "", "cantidad": "", "titulo": "", "autor": "", "precio": ""},
                    {"isbn": "", "codigo": "", "cantidad": "", "titulo": "", "autor": "", "precio": ""},
                    {"isbn": "", "codigo": "", "cantidad": "", "titulo": "", "autor": "", "precio": ""},
                    {"isbn": "", "codigo": "", "cantidad": "", "titulo": "", "autor": "", "precio": ""},
                    {"isbn": "", "codigo": "", "cantidad": "", "titulo": "", "autor": "", "precio": ""},
                    {"isbn": "", "codigo": "", "cantidad": "", "titulo": "", "autor": "", "precio": ""},
                    {"isbn": "", "codigo": "", "cantidad": "", "titulo": "", "autor": "", "precio": ""},
                    {"isbn": "", "codigo": "", "cantidad": "", "titulo": "", "autor": "", "precio": ""},
                    {"isbn": "", "codigo": "", "cantidad": "", "titulo": "", "autor": "", "precio": ""},
                    {"isbn": "", "codigo": "", "cantidad": "", "titulo": "", "autor": "", "precio": ""},
                    {"isbn": "", "codigo": "", "cantidad": "", "titulo": "", "autor": "", "precio": ""}]